import {
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import type { QuizAnswer } from "@/types/quiz";

type Props = {
  studentEmail?: string | null;
  perYear: { year: number; avgTemp: number }[];
  answers: QuizAnswer[] | null;
  solution: {
    input_siswa: string;
    ai_response: string;
    created_at_label: string;
  } | null;
};

export default function ReportView({
  studentEmail,
  perYear,
  answers,
  solution,
}: Props) {
  return (
    <div className="bg-white text-slate-900 p-6 w-198.5">
      <div className="flex items-start justify-between gap-6">
        <div>
          <div className="text-xl font-bold">
            Laporan Investigasi Suhu & Solusi
          </div>
          <div className="text-xs text-slate-500 mt-1">
            Siswa: {studentEmail ?? "-"}
          </div>
        </div>

        <div className="text-xs text-slate-500 text-right">
          <div>{solution?.created_at_label ?? "-"}</div>
          <div>Generated by app</div>
        </div>
      </div>

      <hr className="my-4" />

      <div className="space-y-2">
        <div className="font-semibold">
          Ringkasan Grafik Suhu (versi aplikasi)
        </div>
        <div className="text-xs text-slate-500">
          Catatan: grafik ini untuk laporan (bukan screenshot CODAP).
        </div>

        <div className="h-55 border rounded-md p-2">
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={perYear}>
              <XAxis dataKey="year" tick={{ fontSize: 12 }} />
              <YAxis tick={{ fontSize: 12 }} domain={["auto", "auto"]} />
              <Tooltip />
              <Line
                type="monotone"
                dataKey="avgTemp"
                stroke="#0f172a"
                strokeWidth={2}
                dot={false}
              />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>

      <hr className="my-4" />

      <div className="space-y-2">
        <div className="font-semibold">Jawaban Checkpoint (terakhir)</div>

        {!answers || answers.length === 0 ? (
          <div className="text-sm text-slate-500">
            Belum ada jawaban kuis tersimpan.
          </div>
        ) : (
          <ol className="list-decimal ml-5 text-sm space-y-2">
            {answers.map((a, i) => (
              <li key={i}>
                <div className="text-xs text-slate-500">
                  ID: {a.question_id}
                </div>
                <div className="whitespace-pre-wrap">{a.answer || "-"}</div>
              </li>
            ))}
          </ol>
        )}
      </div>

      <hr className="my-4" />

      <div className="space-y-2">
        <div className="font-semibold">Rencana Aksi Siswa</div>
        <div className="text-sm whitespace-pre-wrap">
          {solution?.input_siswa ?? "-"}
        </div>
      </div>

      <div className="space-y-2 mt-4">
        <div className="font-semibold">Respons AI (Estimasi)</div>
        <div className="text-sm whitespace-pre-wrap">
          {solution?.ai_response ?? "-"}
        </div>
        <div className="text-xs text-slate-500 mt-2">
          Disclaimer: Respons AI adalah estimasi berbasis asumsi umum, bukan
          pengukuran lapangan/prediksi pasti.
        </div>
      </div>
    </div>
  );
}
